# TODO: Configure all values again
version: "3.3"
services:
  api:
    build:
      context: "services/backend-pay" # Replace with source to code
      args:
        - GIT_VERSION
        - GIT_COMMIT
    environment:
      - SAMPLE_ENV

  database:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      PGDATA: /data/postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: my_database
    volumes:
      - ./scripts/postgres-initdb.d:/docker-entrypoint-initdb.d
