version: "3.3"
services:
  # main service or api that is being worked on
  api:
    extends:
      file: ../docker-compose-shared.yml
      service: backend-pay
    # TODO: Dockerfile reference
    # build:
    #   dockerfile: ./Dockerfile.dev
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ../:/workspace:cached
    depends_on:
      - database

  # database for service to connect to
  database:
    extends:
      file: ../docker-compose-shared.yml
      service: database
    environment:
      # TODO: Database envs should go here
      POSTGRES_MULTIPLE_DATABASES: luca-pay
    ports:
      - 5432:5432
    volumes:
      - ./local-data/postgres:/data/postgres

volumes:
  postgres_data:
